### ISSUE TITLE
Update vitest

### ISSUE THREAD

**Issue by gooftroop** [IanVS/vitest-fetch-mock#2]
`SpyInstanceFn` is no longer available in vitest and has been renamed to `SpyInstance`. Is it possible to have vitest updated for this package?

**Comment by IanVS** [comment]
Thanks for the heads up!  If you'd like to submit a PR I'd be happy to merge and release a new version.  Or I can get to it, but it might be a few days.

**Comment by IanVS** [comment]
Thanks for bringing this up, @gooftroop.  A fix has been released in 0.2.0, thanks to @jasikpark.  🙏
