### ISSUE TITLE
Node minimum version

### ISSUE THREAD

**Issue by XaveScor** [IanVS/vitest-fetch-mock#21]
Vitest supports node>=18 only, but vitest-fetch-mock supports node 14 in package.json.

https://github.com/vitest-dev/vitest/blob/d7b0387125da9c2882b12a1f63cc693dc049b15c/package.json#L9

I think, we can safely up the minimum supported Node version up to v18. It allows the lib to use the native fetch instead of cross-fetch polyfill.

**Comment by IanVS** [comment]
Ah, yes, my intention was to support node 18+, I just didn't notice I had an `engines` field.  Would you like to submit a PR?

**Comment by XaveScor** [comment]
I'll make a PR

**Comment by dirkluijk** [comment]
Should be fixed by https://github.com/IanVS/vitest-fetch-mock/pull/24.
