### ISSUE TITLE
fetchMock is not defined after upgrading to 0.4.0

### ISSUE THREAD

**Issue by DotCoyote** [IanVS/vitest-fetch-mock#28]
Hello!

Unfortunately the documentation does not include any migration and I assume fetchMock should be available as before without any changes, but in my NextJS/Typescript Project, I get `ReferenceError: fetchMock is not defined` for all tests using `fetchMock.ANYMETHOD()`.

Anything I'm missing?

**Comment by dirkluijk** [comment]
I think it's because vitest-fetch-mock@0.0.3 was installing `fetchMock` also on the global object. I see this got removed in `0.0.4`. Although I think it's not a good practice to work with globals, it's a breaking change. I will arrange a fix for this.

**Comment by dirkluijk** [comment]
A workaround could be to export your instance of `fetchMock` in the file where you create it:
```
export const fetchMock = createFetchMock(vi);

fetchMock.enableMocks();
```

Otherwise, you could wait for https://github.com/IanVS/vitest-fetch-mock/pull/29 to be merged and released.

**Comment by DotCoyote** [comment]
Could you create a release for this fix? 🙂

**Comment by IanVS** [comment]
0.4.1 is now released.
