### ISSUE TITLE
Started getting `ECONNREFUSED` errors on upgrade to 0.4.1

### ISSUE THREAD

**Issue by morleytatro** [IanVS/vitest-fetch-mock#32]
I was on 0.3.0 with everything working as expected. 0.4.0 caused issues with `fetchMock` not available on the global context so I jumped to 0.4.1, but now none of the fetch calls are getting mocked and just erroring out with `ECONNREFUSED`. Really not sure where the break is, as these are just regular `fetchMock.mockResponseOnce(JSON.stringify({ some: 'val' }))` calls.

Node: 22.11.0

I also tried exporting the fetch mocker and importing to no avail. Adding a second object arg with the status had no effect either. Going to downgrade for now, but would really like to get it situated. Thanks!

**Comment by dirkluijk** [comment]
Please share a link to a repo or steps how to reproduce.

**Comment by morleytatro** [comment]
Yep, I'll try to put a minimal repro together. Wondering if the monorepo setup might have something to do with it, as I was unable to repro with a flat simple example.

**Comment by morleytatro** [comment]
Here's a repro:
https://github.com/morleytatro/vitest-fetch-mock-error

I had some logic in tests that was calling `vi.resetAllMocks()` which was somehow fine in the old version, as I was mocking some other things in the tests that needed resetting per test.

**Comment by dirkluijk** [comment]
I think I know what’s going on. I’ll verify it later today.

**Comment by IanVS** [comment]
Thanks for investigating, @dirkluijk!  

Sounds like maybe this is something to keep in mind when we eventually re-write the readme for this package.

**Comment by morleytatro** [comment]
Thanks @dirkluijk; I suspected that was messing with this lib's functionality under the hood, and the fix worked. Was somewhat strange that downgrading gave me an error in the repro but not in the original, but thanks again.

**Comment by dirkluijk** [comment]
Glad to hear it's resolved! I do agree that it's a bit weird behavior. Would be nice if we can mark some internal mocked functions as excluded, on the other hand, it's doing what it should be doing if you reason about it.
